### ISSUE TITLE
Missing nonterminals

### ISSUE THREAD

**Issue by int3rsys** [binsec/haunted#1]
Hello there,
I'm trying to compile the sources in /src. When executing `make depend`, I receive the following log:
```Targets.mk:336: warning: overriding recipe for target 'dist'
Targets.mk:332: warning: ignoring old recipe for target 'dist'
PIQI piqi/common.piqi
PIQI piqi/instruction.piqi
PIQI piqi/libcall.piqi
PIQI piqi/syscall.piqi
PIQI piqi/dba.piqi
PIQI piqi/trace.piqi
PIQI piqi/analysis_config.piqi
PIQI piqi/config.piqi
PIQI piqi/message.piqi
PIQIML piqi/common_piqi.ml
PIQIML piqi/instruction_piqi.ml
PIQIML piqi/libcall_piqi.ml
PIQIML piqi/syscall_piqi.ml
PIQIML piqi/dba_piqi.ml
PIQIML piqi/trace_piqi.ml
PIQIML piqi/analysis_config_piqi.ml
PIQIML piqi/config_piqi.ml
PIQIML piqi/message_piqi.ml
MENHIR  parser/dbacsl_parser.mli
Warning: 7 states have shift/reduce conflicts.
Warning: 94 shift/reduce conflicts were arbitrarily resolved.
Error: the code back-end requires the type of every nonterminal symbol to be
known. Please specify the type of every symbol via %type declarations, or
enable type inference (look up --infer in the manual).
Type inference is automatically enabled when Menhir is used via Dune,
provided the dune-project file says (using menhir 2.0) or later.
The types of the following nonterminal symbols are unknown:
bin_op
cond
expr
make: *** [../Caml.mk:53: parser/dbacsl_parser.mli] Error 1
```
I believe I have a newer version of menhir, or other dependencies?
Thanks!

**Comment by Lesly-Ann** [comment]
Which version of ocaml and menhir are you using ? I have ocaml `4.05.0` and menhir `20211012` and I can't reproduce the problem.

**Comment by int3rsys** [comment]
Hi @Lesly-Ann , here are the versions:
```
ilyar@ilyar-VirtualBox:~/Downloads/binsec-haunted$ menhir --version
menhir, version 20211230
ilyar@ilyar-VirtualBox:~/Downloads/binsec-haunted$ ocaml --version
The OCaml toplevel, version 4.05.0
```

**Comment by Lesly-Ann** [comment]
I don't have this version of menhir available in my opam switch and I can't reproduce the error with my version.

Maybe you can try to install `opam install menhir.20211012` specifically?

**Comment by Lesly-Ann** [comment]
I added the compilation option that seems to be missing (according to your error message) in https://github.com/binsec/haunted/commit/3d645f80751a361991606e4ee0583de63dada0d7

Let me know if that solves the problem, otherwise you can try to downgrade to `menhir.20211012`.

Finally, if these two solutions do not work, let me know. I asked other Binsec developers and it seems that someone had a similar problem before, so I can try to include their solution in Binsec/Haunted.

**Comment by int3rsys** [comment]
Thanks @Lesly-Ann , now I receive the following error:
```
ilyar@ilyar-VirtualBox:~/Downloads/haunted/src$ make depend
Targets.mk:336: warning: overriding recipe for target 'dist'
Targets.mk:332: warning: ignoring old recipe for target 'dist'
MENHIR  parser/dbacsl_parser.mli
File "parser/dbacsl_parser.mly", line 23, characters 7-10:
Error: Unbound module Dba
make: *** [../Caml.mk:53: parser/dbacsl_parser.mli] Error 1
```
I don't understand much in Ocaml, excuse me.
Note: I downgraded to menhir.20211012 to prevent additional problems.

**Comment by Lesly-Ann** [comment]
Unfortunately, I am not really familiar with the build process so I can't really help much at this point, especially since I've never had such issue before. I am truly sorry about this.
Maybe you can try to use the Docker image?

**Comment by recoules** [comment]
Hi @int3rsys, since you downgraded the `menhir` version, you may want to try building `binsec` from the previous commit 3879d74.

**Comment by Lesly-Ann** [comment]
I confirm: the last commit introduced your last compilation error (sorry about this) so I reverted it.

**Comment by Lesly-Ann** [comment]
I also specified which version of menhir to use in the Makefile so that people won't run into the same problem anymore!

**Comment by int3rsys** [comment]
@Lesly-Ann @recoules Now I'm able to compile successfully. Many thanks :)
