### ISSUE TITLE
Support for x86's LFENCE?

### ISSUE THREAD

**Issue by nmosier** [binsec/haunted#2]
It appears that binsec/haunted doesn't support the LFENCE instruction, which acts a full speculation barrier and is a common mitigation for speculative execution vulnerabilities.
I am trying to verify a LFENCE-based mitigation using binsec/haunted, but if it doesn't support LFENCE, it can't verify that the mitigation prevents secrets from leaking speculatively.

Would it be possible to add LFENCE support? All it needs to do is stop speculation whenever an LFENCE is encountered.

**Comment by Lesly-Ann** [comment]
Thanks for your interest in Binsec/Haunted!

I actually have some support for `fence` in Binsec/Rel, but funnily not in Binsec/Haunted. I'll try to port the support for fences here. It should be easy :)

**Comment by Lesly-Ann** [comment]
I came up with something yesterday evening, but I haven't had time to test it. I won't have time to do so in the next two weeks, so if you try it in the meantime, let me know if it works as expected or not!

It only supports `mfence` instructions for now. But with respect to Spectre-PHT and Spectre-STL, it should be the same whether you have an mfence or lfence iirc? Let me know if that work for you or not (and if not I can trivially add support for other serializing instructions).

**Comment by nmosier** [comment]
Okay great, thanks! I'll test it out soon, hopefully within the next day. (I don't think `mfence` has the same speculation-halting effect as `lfence`, but I can just replace `lfence`s with `mfence`s for now)

**Comment by nmosier** [comment]
I tested out the fence support you pushed, and it works great! Thanks for the quick turnaround!
